### ISSUE TITLE
誤植ぽいところ

### ISSUE THREAD

**Issue by zukakosan** [tbuchi888/cicd-handson-aca-webapp#1]
今更ながら一通り試させていただきました！ありがとうございます。
誤植っぽいところだけ1つ。

対象ファイル：https://github.com/tbuchi888/cicd-handson-aca-webapp/blob/main/05-webapp-manual-deploy.md

ここのオペレーティングシステムは、Linux ですかね？
Windows も記載されていたので。
![image](https://github.com/tbuchi888/cicd-handson-aca-webapp/assets/25217308/573b89a3-0ff3-4bd4-b995-efe35e059f2c)

**Comment by tbuchi888** [comment]
ありがとうございます。修正しました。
改行により、のこったままになっていたようです。

**Comment by tbuchi888** [comment]
[03742f5a3496785064d2b3fd957973f296d791dc](https://github.com/tbuchi888/cicd-handson-aca-webapp/commit/03742f5a3496785064d2b3fd957973f296d791dc)
